---
title: 'Week 13: Global Alcohol Consumption'
author: Joe Stoica
date: 6/29/2018
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
library(knitr)
library(kableExtra)
```

```{r read in data}
# Windows
#consumption <- read_csv("C:/Users/Joe/Documents/Github/tidytuesday/data/week13_alcohol_global.csv")

# Mac
consumption <- read_csv("/Users/Joe/Documents/Github/tidytuesday/data/week13_alcohol_global.csv")
```

```{r 538 table remake}
beer <- consumption %>% 
  select(country, Beer = beer_servings) %>% 
  top_n(10) %>% 
  arrange(desc(Beer))

spirit <- consumption %>% 
  select(country, Spirit = spirit_servings) %>% 
  top_n(10) %>% 
  arrange(desc(Spirit))

wine <- consumption %>% 
  select(country, Wine = wine_servings) %>% 
  top_n(10) %>% 
  arrange(desc(Wine))

alcohol <- bind_cols(beer, spirit, wine)

alcohol %>% 
  kable(caption = "Who Drinks The Most Beer, Spirits, And Wine?",
        col.names = c("", "BEER", "", "SPIRIT", "", "WINE")) %>% 
  kable_styling() 
```

```{r top 20 plot}
top10 <- consumption %>% 
  top_n(10) %>% 
  select(country, Beer = beer_servings, Spirits = spirit_servings, Wine =  wine_servings) %>% 
  gather(key = drink, value = qty, -country) %>% 
  group_by(country)

top20 <- consumption %>% 
  top_n(20) %>% 
  select(country, Beer = beer_servings, Spirits = spirit_servings, Wine =  wine_servings) %>% 
  gather(key = drink, value = qty, -country) %>% 
  group_by(country)


plot <- ggplot(top20, aes(reorder(country, qty),
                  qty,
                  fill = drink)) +
  geom_bar(stat = "identity")+
  theme_fivethirtyeight() +
  coord_flip() +
  theme(axis.title = element_text(),
        axis.title.y = element_blank(),
        plot.title = element_text(hjust = 1),
        legend.position = "top",
        legend.text = element_text(size = 14)) +
  ylab("Servings") +
  ggtitle("Top 20 Consumers of Pure Alcohol By Drink Type") +
  guides(fill = guide_legend(keywidth = 3,
                             keyheight = .75, 
                             title=NULL, 
                             label.position = "top", 
                             label.hjust = 0.5,
                             reverse = TRUE)) +
  scale_fill_manual(values = c("#0392cf", "#7bc043", "#ee4035"))

plot


#ggsave("top20.png", plot)
```

```{r sankey}
library(devtools)
install_github("mages/googleVis")
require(googleVis)

sankey <- plot(gvisSankey(top10,
                          from = "country",
                          to = "drink",
                          weight = "qty",
                          option = "list"(
                            height = 750,
                            sankey = "{link:{color:{fill:'light blue'}}}"
                          )))
```



